services:
  api:
    build: .
    environment:
      DD_AGENT_HOST: datadog-agent
      DD_TRACE_AGENT_PORT: 8126
      REDIS_ADDR: redis:6379
      REDIS_USE_TLS: "false"
    ports:
      - "8000:8000"
    depends_on:
      - redis

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"

  datadog-agent:
    image: gcr.io/datadoghq/agent:latest
    environment:
      - DD_API_KEY=dummy
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
    ports:
      - "8126:8126"
