FROM golang:1.25-alpine

WORKDIR /app

ARG ORCHESTRION_VERSION=v1.9.0

RUN apk add --no-cache ca-certificates git

COPY go.mod go.sum ./
RUN go mod download && GOSUMDB=off go install github.com/DataDog/orchestrion@"${ORCHESTRION_VERSION}" && go install gotest.tools/gotestsum@latest

COPY . .

# Default command for the test container
CMD ["gotestsum", "--", "./..."]
