FROM golang:1.25-alpine

WORKDIR /app

RUN apk add --no-cache git

COPY go.mod go.sum ./
RUN go mod download && go install github.com/DataDog/orchestrion@latest && go install gotest.tools/gotestsum@latest

COPY . .

# Default command for the test container
CMD ["gotestsum", "--", "./..."]
