development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: >-
    <%= ENV.fetch("REDIS_URL") { password = ENV.fetch("REDIS_PASSWORD", nil); addr = ENV.fetch("REDIS_ADDR", "localhost:6379"); db = ENV.fetch("REDIS_DB", "1"); password ? "redis://:#{password}@#{addr}/#{db}" : "redis://#{addr}/#{db}" } %>
  channel_prefix: rails_app_production
