name: example
values:
  - key: base_url
    value: ''
    enabled: true
  - key: api_version
    value: /v0
    enabled: true
  - key: api_base
    value: '{{base_url}}{{api_version}}'
    enabled: true
  - key: client_id
    value: ''
    enabled: true
  - key: client_secret
    value: ''
    enabled: true
  - key: access_token
    value: ''
    enabled: true
  - key: token_expiry
    value: ''
    enabled: true
  - key: auth_base
    value: ''
    enabled: true
