name: Docker Build

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "rails-app/**"
      - ".github/workflows/docker-build.yml"
      - "public.jwk"

permissions:
  contents: read

jobs:
  build:
    name: build
    runs-on: "codebuild-emmy-github-runner-emmy-api-${{ github.run_id }}-${{ github.run_attempt }}"
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v6

      - name: Docker Build
        run: docker build rails-app
