name: Docker Build

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "**/*.go"
      - ".dockerignore"
      - "Dockerfile"
      - "go.mod"
      - "go.sum"
      - "public.jwk"

permissions:
  contents: read

jobs:
  build:
    name: build
    runs-on: "emmy-github-runner-emmy-api-${{ github.run_id }}-${{ github.run_attempt }}"
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v6

      - name: Docker Build
        run: docker build .
