name: PR Verification
permissions:
  contents: read
  pull-requests: read

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "rails-app/**"
      - ".github/workflows/pr.yml"

jobs:
  rspec:
    name: rspec
    runs-on: "codebuild-emmy-github-runner-emmy-api-${{ github.run_id }}-${{ github.run_attempt }}"
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: emmy
          POSTGRES_PASSWORD: emmy
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    container:
      image: ruby:3.4.9-slim
      env:
        RAILS_ENV: test
        DB_HOST: postgres
        DB_USER: emmy
        DB_PASSWORD: emmy
        REDIS_ADDR: redis:6379

    steps:
      - name: Fetch Repository
        uses: actions/checkout@v6

      - name: Install system dependencies
        run: |
          apt-get update -qq
          apt-get install --no-install-recommends -y build-essential git libpq-dev curl

      - name: Install gems
        working-directory: rails-app
        run: |
          gem install bundler
          bundle install

      - name: Wait for Database
        run: |
          until printf "" 2>>/dev/tcp/postgres/5432; do
            echo "Waiting for postgres..."
            sleep 1
          done
        continue-on-error: true

      - name: Setup Database
        working-directory: rails-app
        run: |
          bin/rails db:prepare

      - name: Run RSpec
        working-directory: rails-app
        run: |
          bundle exec rspec

  rubocop:
    name: rubocop
    runs-on: "codebuild-emmy-github-runner-emmy-api-${{ github.run_id }}-${{ github.run_attempt }}"
    container:
      image: ruby:3.4.9-slim
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v6

      - name: Install system dependencies
        run: |
          apt-get update -qq
          apt-get install --no-install-recommends -y build-essential git

      - name: Install gems
        working-directory: rails-app
        run: |
          gem install bundler
          bundle install

      - name: RuboCop
        working-directory: rails-app
        run: |
          bundle exec rubocop
