name: Publish Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  publish:
    name: push image
    runs-on: self-hosted
    outputs:
      image_tag: ${{ steps.derive-image-tag.outputs.image_tag }}
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v6

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Derive image tag
        id: derive-image-tag
        shell: bash
        run: |
          echo "IMAGE_TAG=${GITHUB_SHA::7}" >> "$GITHUB_ENV"
          echo "image_tag=${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"

      - name: Log in to Artifactory
        uses: docker/login-action@v3
        with:
          registry: artifactory.cloud.cms.gov
          username: ${{ secrets.ARTIFACTORY_USERNAME }}
          password: ${{ secrets.ARTIFACTORY_PASSWORD }}

      - name: Push Docker image
        run: ./scripts/push-image

  deploy:
    name: deploy ${{ matrix.env_name }}
    needs: publish
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        env_name:
          - dev
          # - test
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v6

      - name: Deploy to ECS
        env:
          AWS_REGION: us-east-1
          IMAGE_TAG: ${{ needs.publish.outputs.image_tag }}
        run: ./scripts/deploy-ecs "${{ matrix.env_name }}"
